# Generated by Django 5.0.6 on 2024-06-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Designation',
            new_name='Designations',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Name',
            new_name='Names',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Password',
            new_name='Passwords',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Username',
            new_name='Usernames',
        ),
    ]
