# Generated by Django 5.0.6 on 2024-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0002_rename_designation_registration_designations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dispatchform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dispatch_by', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('track_id', models.CharField(max_length=100)),
                ('sent_by', models.CharField(max_length=100)),
                ('file_no', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
