# Generated by Django 5.0.6 on 2024-06-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0003_dispatchform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchform',
            name='data',
        ),
    ]
