# Generated by Django 5.0.6 on 2024-06-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0005_dispatchform_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='reciveform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Receive_date', models.DateField(null=True)),
                ('Received_by', models.CharField(max_length=100)),
                ('File_no', models.CharField(max_length=100)),
                ('Remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
