# Generated by Django 5.0.6 on 2024-06-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0006_reciveform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reciveform',
            new_name='receiveform',
        ),
    ]
