# Generated by Django 5.0.6 on 2024-06-27 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0007_rename_reciveform_receiveform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveform',
            old_name='From',
            new_name='Froms',
        ),
    ]
