# Generated by Django 5.0.6 on 2024-06-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0008_rename_from_receiveform_froms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveform',
            old_name='Froms',
            new_name='From',
        ),
    ]
