# Generated by Django 5.0.6 on 2024-07-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0009_rename_froms_receiveform_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
