# Generated by Django 5.0.6 on 2024-07-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchform',
            name='dispatch_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stqcapp.category'),
        ),
    ]
