# Generated by Django 5.0.6 on 2024-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stqcapp', '0011_alter_dispatchform_dispatch_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchform',
            name='dispatch_by',
            field=models.CharField(max_length=100),
        ),
    ]
