# Generated by Django 5.0.6 on 2024-07-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='Category',
        ),
    ]
