# Generated by Django 5.0.6 on 2024-07-05 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_mydata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mydata',
            name='user',
        ),
    ]
