# Generated by Django 5.0.6 on 2024-07-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_user',
            old_name='password',
            new_name='password3',
        ),
        migrations.RenameField(
            model_name='login_user',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='login_user',
            old_name='username',
            new_name='username2',
        ),
    ]
